### ISSUE TITLE
That network make the page crash

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#528]
```toml
Name = "fail"
LogLevel = "info"
TokenExpiry = "168h0m0s"
Port = 1789
Host = "127.0.0.1"

[API]
  [API.GRPC]
    Hosts = ["does.not.work:42"]
    Retries = 5
```

<img width="872" alt="Screenshot 2023-02-23 at 11 41 11" src="https://user-images.githubusercontent.com/4662842/220884241-afec7ce7-619c-4c01-a4e7-84f31037c2b5.png">
